### ISSUE TITLE
Use correct "committer" on merge

### ISSUE THREAD

**Issue by rjernst** [elastic/jarvis#16]
Currently all PRs merged by Jarvis look like they were merged by @jordansissel.  That is cool and all, but any problems should be pointed at the person doing the merge (ie telling jarvis to merge), but this information is lost.

**Comment by jordansissel** [comment]
Example of this: https://github.com/elasticsearch/elasticsearch/pull/9445

+1

**Comment by jordansissel** [comment]
@rjernst I'm also open to having the bot comment say who requested the merge in the "Merged into <xxx>" comment- thoughts?

**Comment by rjernst** [comment]
@jordansissel That would be better than the current behavior at least?

**Comment by jordansissel** [comment]
@rjernst I was proposing both correct-git-committer and also a message "@so-and-so initiated this merge"

**Comment by jordansissel** [comment]
#39 fixes this, but it will be a little while before this is actually deployed.

**Comment by jordansissel** [comment]
Solved in master. Will be deployed soon.

**Comment by jordansissel** [comment]
Solution will be telling jarvis your git-email via hipchat message `@jarvis user set git-email ...`
