### ISSUE TITLE
Merge comment should bold and clearly separate branch names

### ISSUE THREAD

**Issue by rjernst** [elastic/jarvis#17]
Currently the list of branches jarvis merged into is inline as normal text, and not separated at all.  It would be useful to clearly mark this, perhaps like this:

> Merged sucessfully into `master` and `1.x`!

ie monospace the branch names, and separate them with commas, and the last two with "and".

**Comment by jordansissel** [comment]
+1

**Comment by ph** [comment]
fixed in the latest version.
