### ISSUE TITLE
Add correct labels for each branch

### ISSUE THREAD

**Issue by rjernst** [elastic/jarvis#20]
In the elasticsearch project, we use concrete versions for branches.  So `master` is `v2.0.0` and, at the moment, `1.x` is `1.5.0`.  Jarvis currently does not add any label when merging to master, and adds `1.x` branch of the same name.

**Comment by jordansissel** [comment]
+1

**Comment by jordansissel** [comment]
Proposal:

* Jarvis should have a mapping of project branch-to-label names and use these when merging.
* The configuration of this mapping should be available through commands via Jarvis.

Configuration example:
```
Jordan: @Jarvis label elasticsearch/elasticsearch master v2.0.0
Jarvis: Label for elasticsearch/elasticsearch `master` branch is now v2.0.0
```

**Comment by jordansissel** [comment]
#39 brings in a kind of 'settings' functionality and we could have per-project settings such as branch-label mappings. Progress, but not yet ready.

**Comment by jordansissel** [comment]
Bumping this as this was brought up today in a discussion with the logstash team.

**Comment by jordansissel** [comment]
I rewrote this as #85.
