### ISSUE TITLE
Allow jarvis to publish devutils and logstash-core gems

### ISSUE THREAD

**Issue by purbon** [elastic/jarvis#28]
Currently jarvis depends on having some commends avaialble because of the plugins, this prevents us to release devutils or logstash-core.

We should make be able to release logstash-devutils and logstash-core with jarvis as it prevents people from forgetting steps :+1: 

/cheers

**Comment by ph** [comment]
#46 should fix that by not running `rake vendor` if the repo doesn't have a vendor.json file.
