### ISSUE TITLE
Commit messages are strict ASCII and doesn't correctly handler accented characters

### ISSUE THREAD

**Issue by ph** [elastic/jarvis#40]
reported by @magnusbaeck

It seems the elasticsearch-bot bot that listens to GitHub PR threads and merges them when it sees "LGTM" from a core maintainer assumes that commit messages are strict ASCII and so doesn't perform RFC2047 decoding of them. My original commit in https://github.com/logstash-plugins/logstash-filter-cidr/pull/4 was badly mangled.

**Comment by jordansissel** [comment]
Interesting. TIL.

Should be an easy fix.
