### ISSUE TITLE
Jarvis not creating a tag when publishing

### ISSUE THREAD

**Issue by purbon** [elastic/jarvis#51]
I just published a new version (2.0.5) of https://github.com/logstash-plugins/logstash-input-tcp but the tag is not there. I understand Jarvis failed to create it, this is important to get fix.

**Comment by purbon** [comment]
creating the tag manually now in order not to loss history.

**Comment by ph** [comment]
@jordansissel I believe this is a permission issue, can you verify that?

**Comment by jordansissel** [comment]
We fixed this. The problem was `rake publish_gem` was running without SSH_AUTH_SOCK being set (specifically, it was unset before running! Oops!). That's been fixed.

**Comment by jordansissel** [comment]
Specifically, this commit: 2802eefdbb58e3e48b00fce4f834d5441595dd38
