### ISSUE TITLE
PR should be able to merge with a merge commit 

### ISSUE THREAD

**Issue by jordansissel** [elastic/jarvis#54]
It'd be nice if the branch targeted for a PR (like to master) was merged as a merge commit. Kibana team and others may like it.

For example, in this screenshot:

<img width="509" alt="screen shot 2015-11-25 at 3 32 57 pm" src="https://cloud.githubusercontent.com/assets/131818/11411849/da5995a0-9389-11e5-9fb4-e2547b0d027d.png">

The PR is targeting the `elastic` org's `kibana` repo at `master` branch, so, propsing new behavior here for Jarvis:
- If `merge` is given no branches, assume `master` (specifically, assume the _target branch_ of the PR). Example: `jarvis merge https://some/url` (with no branch)
- Use a merge commit to merge the main target instead of `git am`-style.

Doing this will have some nice benefits:

1) Implicit default branch for a PR's merge makes the user experience a little clearer, I hope.
2) Using a merge commit will cause GitHub to show the PR as `merged` instead of `closed`

---

I'd like to propose that this be a default behavior:
- If no branches are specified, default to the target branch of the PR
- When merging to the target branch of a PR, always use a merge commit
- Any branches being merged into via Jarvis that are not the target branch will be merged using the current merge strategy (`git am`)

**Comment by spalger** [comment]
:+1: This is currently the strategy we use on the Kibana team. I like that Github knows which prs/branches have been merged and which have been rejected.

**Comment by epixa** [comment]
For Kibana, we'll want jarvis to be able to not only do a merge commit to the target branch of the PR but *also* specify other branches to backport (without merge commits).  I couldn't tell from the issue description whether that was the proposal or not.

**Comment by jordansissel** [comment]
> we'll want jarvis to be able to not only do a merge commit to the target branch of the PR but also specify other branches to backport (without merge commits)

@epixa Yep! That is what I was wanting also based on discussion with @w33ble, @spalger, and others.

**Comment by w33ble** [comment]
> When merging to the target branch of a PR, always use a merge commit

The way I read that, that's how it's work. So doing a `jarvis merge url/to/1234 master 4.4 4.3` would do the `git am` step on 4.3 and 4.4, but do a merge commit on master (assuming it was the target for the PR). Sounds like we're all in agreeance ;)

**Comment by jordansissel** [comment]
Logstash team talked about this today and we remembered that we wanted merge commits on the target branch also. I'll work on this.
