### ISSUE TITLE
Tell jarvis about PRs folks want to get reviewed

### ISSUE THREAD

**Issue by jordansissel** [elastic/jarvis#73]
There's a tremendous amount of signal on various channels (email, slack, etc) such that important signals are getting lost. For example, we sometimes accidentally neglect PRs, and we'd like to fix that. There are many PRs where there is no obvious assignee. There's also individuals who end up receiving more PR assignments (out of habit, accident, etc) than others.

Jarvis could help keep us notified about PRs that are aging or important.

Proposal:

* Allow assigning a PR to Jarvis to put this in the Jarvis queue for PRs needing a dedicated reviewer.
* Add Jarvis command to queue a PR (which should assign it to itself for tracking)
* Add Jarvis command to ask for queued PRs (ones assigned to Jarvis?)
* Periodic pinging the #logstash channel to remind about unattended PRs

/cc @andrewvc

**Comment by andrewvc** [comment]
@jordansissel also, periodic blabbing to a channel about stuff needing to be looked at!

**Comment by jordansissel** [comment]
@andrewvc oh yeah! I have updated the proposal to include this now.

**Comment by andrewvc** [comment]
After discussing with @jordansissel  the MVP will work as follows:

## Adding a PR
- Users assign a PR by issuing a slack command in the channel: @jarvis review <LINK_TO_PR>
- Jarvis responds by saying: 'Thanks for the PR! Consider reviewing some of the following open PRs: (displays list of PRs opened by other users)'

## Nagging
- Jarvis posts in the chat once every N hours (configured in lita_config.rb) the results of a github search for PRs assigned to @jarvis 

## Ask for PRs command
- Sending the command: @jarvis reviews will display the nag message.

**Comment by ph** [comment]
this was implemented in #74
