### ISSUE TITLE
Jarvis `plugins` command is  broken

### ISSUE THREAD

**Issue by ph** [elastic/jarvis#87]
The command to check the travis status for all the default plugins is broken.
```
[08:43] 
jarvisAPP (boom) Unhandled exception: NoMethodError - undefined method `[]' for nil:NilClass


[08:43] 
/home/jarvis/jarvis/lib/jarvis/travis/watchdog.rb:27:in `block (2 levels) in get_status'
/home/jarvis/jarvis/lib/jarvis/travis/watchdog.rb:27:in `each'
/home/jarvis/jarvis/lib/jarvis/travis/watchdog.rb:27:in `each_with_object'
/home/jarvis/jarvis/lib/jarvis/travis/watchdog.rb:27:in `block in get_status'
/home/jarvis/jarvis/lib/jarvis/travis/watchdog.rb:22:in `each'
/home/jarvis/jarvis/lib/jarvis/travis/watchdog.rb:22:in `get_status'
/home/jarvis/jarvis/lib/jarvis/travis/watchdog.rb:50:in `execute'
/home/jarvis/jarvis/lib/jarvis/travis/watchdog.rb:63:in `execute'
/home/jarvis/jarvis/lib/jarvis/commands/plugins.rb:11:in `execute'
/home/jarvis/.rvm/gems/ruby-2.4.0/gems/clamp-1.0.1/lib/clamp/command.rb:68:in `run'
/home/jarvis/jarvis/lib/jarvis/clamp_delegate.rb:56:in `block in callback'
/home/jarvis/jarvis/lib/jarvis/mixins/pool_delegate.rb:16:in `block in pool_execute'
``

**Comment by jsvd** [comment]
works now:

> João Duarte  14:27
> status
> jarvis 14:27
> Oops, We have currently have 22 plugins jobs failing :sadbazpanda: (100 plugins checked)
> Failures for branch: master
> logstash-codec-collectd, logstash-codec-netflow, logstash-filter-anonymize, logstash-filter-dissect, logstash-filter-elasticsearch, logstash-filter-fingerprint, logstash-filter-grok, logstash-filter-json, logstash-filter-mutate, logstash-filter-split, logstash-filter-throttle, logstash-filter-translate, logstash-filter-urldecode, logstash-input-elasticsearch, logstash-input-ganglia, logstash-input-graphite, logstash-input-http_poller, logstash-input-pipe, logstash-input-s3, logstash-input-unix, logstash-output-email, logstash-output-sns
